# Generated by Django 4.2.5 on 2023-10-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
