# Generated by Django 4.2.5 on 2023-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title1',
            field=models.CharField(default='text', max_length=40),
        ),
    ]
