# Generated by Django 4.2.5 on 2023-10-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0008_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='upload/Products')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.categorie')),
            ],
        ),
    ]
