# Generated by Django 4.2.6 on 2023-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='upload/services/'),
        ),
    ]
