# Generated by Django 4.2.6 on 2023-10-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0026_remove_slider_name_slider_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='s_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
