# Generated by Django 4.2.5 on 2023-10-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0027_alter_slider_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/services/'),
        ),
    ]
