# Generated by Django 4.2.5 on 2023-10-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0028_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='servie_name',
            new_name='service_name',
        ),
    ]
